"""
src/aws/parser.py

Deterministic Local Parser.
Reads the frozen JSON files from the data directory and normalizes the AWS 
chaos into strict Pydantic models (PolicyStatement, ResourceData) for the Z3 engine.
"""

import json
import os
from typing import Dict, Any, List, Tuple
from src.models import PolicyStatement, ResourceData

# Fallback map for the demonstration mode
DEMO_ROLE_MAP = {
    "DevTeam-Junior": "policy_devteam.json",
    "DataEng-Team": "policy_dataeng.json",
}

def _load_json(filepath: str) -> Dict[str, Any]:
    """Safely loads a JSON file from disk."""
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Missing required data file: {filepath}")
    with open(filepath, 'r', encoding='utf-8') as f:
        return json.load(f)

def fetch_local_iam_policy(role_name: str, data_dir: str) -> Dict[str, Any]:
    """
    Looks for the requested role in the frozen IAM export.
    If not found (or in demo mode), falls back to the mock policy files.
    """
    export_path = os.path.join(data_dir, "iam_roles_export.json")
    
    # 1. Try to find the role in the real export generated by sync_aws.py
    if os.path.exists(export_path):
        roles_export = _load_json(export_path)
        for role in roles_export:
            if role.get("RoleName") == role_name:
                print(f"  [Parser] Loaded real IAM policy for '{role_name}'")
                # For simplicity in the engine, we return the first inline policy document
                policies = role.get("InlinePolicies", [])
                if policies:
                    return policies[0].get("PolicyDocument", {})
                return {"Statement": []} # Empty policy if no inline policies exist

    # 2. Fallback to Demo mode (Mocks)
    filename = DEMO_ROLE_MAP.get(role_name)
    if filename:
        filepath = os.path.join(data_dir, filename)
        print(f"  [Parser] Loaded mock IAM policy for '{role_name}' from {filename}")
        raw_mock = _load_json(filepath)
        # Handle the structure of our mock files
        if "PolicyDocument" in raw_mock:
            return raw_mock["PolicyDocument"]
        return raw_mock
        
    raise ValueError(f"Role '{role_name}' not found in real export or demo mocks.")

def fetch_local_prices_and_quotas(data_dir: str) -> Dict[str, Any]:
    """Loads the frozen public prices and AWS Service Quotas."""
    filepath = os.path.join(data_dir, "aws_prices_quotas.json")
    print("  [Parser] Loading offline prices and quotas")
    return _load_json(filepath)

def parse_policy_statements(policy: Dict[str, Any]) -> List[PolicyStatement]:
    """
    Normalizes the chaotic IAM JSON structure into strictly typed Pydantic objects.
    """
    statements = []
    
    # In AWS, 'Statement' can be a dict (if there's only one) or a list.
    raw_statements = policy.get("Statement", [])
    if isinstance(raw_statements, dict):
        raw_statements = [raw_statements]

    for stmt in raw_statements:
        # Normalize Actions to List
        actions = stmt.get("Action", [])
        if isinstance(actions, str):
            actions = [actions]

        # Normalize Resources to List
        resources = stmt.get("Resource", ["*"])
        if isinstance(resources, str):
            resources = [resources]

        # Use Pydantic to validate and construct the object
        statements.append(PolicyStatement(
            sid=stmt.get("Sid", "UnnamedStatement"),
            effect=stmt.get("Effect", "Deny"),
            actions=actions,
            resources=resources
        ))

    return statements

def extract_allowed_instances(policy: Dict[str, Any]) -> List[str]:
    """
    Extracts allowed EC2 instance types by evaluating 'ec2:RunInstances'.
    Returns ["*"] if the user has unrestricted EC2 access.
    """
    allowed_types = []
    
    raw_statements = policy.get("Statement", [])
    if isinstance(raw_statements, dict):
        raw_statements = [raw_statements]

    for stmt in raw_statements:
        if stmt.get("Effect") != "Allow":
            continue
            
        actions = stmt.get("Action", [])
        if isinstance(actions, str):
            actions = [actions]
            
        if "ec2:RunInstances" not in actions and "*" not in actions:
            continue

        # Check if there's a specific condition restricting the instance type
        condition = stmt.get("Condition", {}).get("StringEquals", {})
        
        if "ec2:InstanceType" in condition:
            types = condition["ec2:InstanceType"]
            if isinstance(types, str):
                allowed_types.append(types)
            else:
                allowed_types.extend(types)
        else:
            # If there's an Allow for RunInstances without conditions, everything is allowed
            return ["*"]

    return allowed_types

def parse_resources(
    prices_data: Dict[str, Any],
    allowed_instances: List[str],
) -> Tuple[List[ResourceData], int]:
    """
    Cross-references the price catalog with the instance types allowed by IAM.
    Returns typed ResourceData objects for the Z3 ILP solver.
    """
    global_quota = prices_data.get("global_vcpu_quota", 64)
    resources = []
    
    for res in prices_data.get("resources", []):
        is_allowed = ("*" in allowed_instances) or (res["id"] in allowed_instances)
        
        resources.append(ResourceData(
            id=res["id"],
            cost_per_hour=res["cost_per_hour"],
            vcpu_cost=res["vcpu"],
            max_qty=res.get("max_qty", 100),
            allowed=is_allowed
        ))

    return resources, global_quota